version: '3.1'

services:
  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - 5672:5672

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass secret --appendonly yes
    volumes:
      - gateway-redis-data:/data

  db:
    image: postgres
    restart: always
    volumes:
      - gateway-postgres-data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: secret

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  
  rates_collector:
    image: ratescollector
    restart: always
    depends_on:
      - db
      - redis

  stats_collector:
    image: statisticscollector
    restart: always
    depends_on:
      - db
      - rabbitmq
    expose:
      - 80

  rates_gateway_api:
    image: ratesgatewayapi
    restart: always
    depends_on:
      - db
      - redis
      - stats_collector
    expose:
      - 80

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rates_gateway_api
    ports:
      - 4000:4000

volumes:
  gateway-postgres-data:
  gateway-redis-data: