version: '3.1'

services:
  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - 5672:5672

  redis:
    image: redis
    restart: always

  db:
    image: postgres
    restart: always
    volumes:
      - gateway-postgres-data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: secret

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  
  rates_collector:
    image: ratescollector
    restart: always
    depends_on:
      - db
      - redis

volumes:
  gateway-postgres-data: